!!python/object:argparse.Namespace
a_dim: 8
add_inner_to_outer_loss: false
advection_emb: false
baseline: false
batch_norm_to_group_norm: true
batch_size: 16
burgers_emb: true
center_crop: 1080
channels: 1
ckpt_every: 10
conv_emb: false
crop_upper_right: 1080
data_root: /data/divyam123/fenics_fixed
dataset: 1d_burgers_multiparam
emb_dim: 64
emb_type: conserved
enc_dec_type: vgg
encoder_emb: false
fixed_ic: false
fixed_window: false
fno_layers: 3
fno_modes: 16
fno_width: 64
frame_step: 1
g_dim: 128
horiz_flip: true
image_width: 128
inner_crit_compare_to: prev
inner_crit_mode: mse
inner_lr: 0.0001
inner_opt_all_model_weights: true
last_frame_skip: false
learn_inner_lr: false
log_dir: ./results_summer_new/burgers/
max_step: 4
model_path: ''
n_epochs: 200
n_eval: 4
n_future: 2
n_past: 2
no_teacher_force: false
nsample: 100
num_emb_frames: 150
num_epochs_per_val: 1
num_inner_steps: 1
num_jump_steps: 0
num_learned_parameters: 1
num_param_combinations: -1
num_threads: 0
num_train_batch: -1
num_trials: 1
num_val_batch: -1
only_cn_decoder: false
only_tailor_on_improvement: false
only_twenty_degree: true
optimize_emb_enc_params: false
outer_lr: 0.001
outer_opt_model_weights: true
param_loss: false
pde_const_emb: false
pde_emb: false
plot_train: 0
posterior_rnn_layers: 1
prior_rnn_layers: 1
random_weights: true
reload_best: false
reload_checkpoint: false
reuse_lstm_eps: true
save_checkpoint: false
seed: 1
stack_frames: false
stop_grad: false
svg_loss_kl_weight: 0
tailor: true
test_set_length: -1
train_embedding: true
train_set_length: -1
use_action: 0
use_partials: true
val_inner_lr: 0.0001
verbose: false
warmstart_emb_path: ''
z_dim: 64
