!!python/object:argparse.Namespace
a_dim: 8
add_inner_to_outer_loss: false
baseline: false
batch_norm_to_group_norm: true
batch_size: 8
center_crop: 1080
channels: 2
ckpt_every: 10
ckpt_inner_loss: true
ckpt_outer_loss: true
ckpt_svg_loss: false
crop_upper_right: 1080
data_root: /data/nithinc/pdebench/new_parameters/2D/ReactionDiffusion
dataset: 2d_reacdiff_multiparam
emb_dim: 64
emb_type: pde_emb
enc_dec_type: vgg
encoder_emb: false
fixed_ic: false
fixed_window: false
fno_layers: 4
fno_modes: 16
fno_width: 256
frame_step: 1
g_dim: 128
horiz_flip: true
image_width: 128
inner_crit_compare_to: pde_log
inner_crit_mode: mse
inner_lr: 0.0001
inner_opt_all_model_weights: true
last_frame_skip: false
learn_inner_lr: false
log_dir: ./results_noether_summer/fixedtrainvalsplit_perturbed_experiments_npast=1_nfuture=1/
max_step: 4
model_path: ./checkpoints/pdes/t_past2/batch_5d
n_epochs: 500
n_eval: 4
n_future: 2
n_past: 2
no_teacher_force: false
nsample: 100
num_emb_frames: 2
num_epochs_per_val: 1
num_inner_steps: 1
num_jump_steps: 0
num_learned_parameters: 1
num_param_combinations: -1
num_threads: 0
num_train_batch: -1
num_trials: 1
num_val_batch: -1
only_cn_decoder: false
only_tailor_on_improvement: false
only_twenty_degree: true
optimize_emb_enc_params: false
outer_lr: 0.0001
outer_opt_model_weights: true
pinn_outer_loss: true
plot_train: 0
posterior_rnn_layers: 1
prior_rnn_layers: 1
random_weights: true
reload_best_inner: false
reload_best_outer: false
reload_best_svg: false
reload_latest: false
reuse_lstm_eps: true
save_checkpoint: true
seed: 1
stack_frames: false
stop_grad: false
svg_loss_kl_weight: 0
tailor: false
test_set_length: -1
train_noether: true
train_set_length: -1
use_action: 0
use_partials: true
val_inner_lr: 0.0001
verbose: false
warmstart_emb_path: /home/sanjeevr/noether-networks/results_summer/fixedtrainvalsplit_pderesidualloss_onlylearnk_lr1e-3_bs16_use_partials_fixedpderesidual_2embframes/Tue-Jun-20-02.31.39-2023_past=2_future=2_tailor=PDE/best_ckpt_model.pt
z_dim: 64
